# Generated by Django 5.2.16 on 2026-07-27 01:17

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='accepts_submissions',
            field=models.BooleanField(default=False, help_text="If on, guardians can attach a file against this homework and this item's detail page shows a submitted/late/missing roster for the class, the same way permission-slip responses do. Off by default — existing homework is unaffected until a teacher opts in."),
        ),
        migrations.AlterField(
            model_name='homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homework/%Y/%m/', validators=[core.models.validate_attachment_size]),
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='homework_submissions/%Y/%m/', validators=[core.models.validate_attachment_size, core.models.validate_submission_extension])),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late')], max_length=10)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='core.student')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Which linked guardian actually submitted/replaced this. Any guardian linked to the student can submit or replace — same multi-guardian-household support GuardianLink provides elsewhere — so this is informational for the teacher roster, not an access restriction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_submissions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('homework', 'student'), name='unique_submission_per_student')],
            },
        ),
    ]
