# Generated by Django 5.2.16 on 2026-07-28 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homework_accepts_submissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="e.g. 'Independence Day' or 'Term 1 break'", max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Same as start date for a single closed day.')),
                ('event_type', models.CharField(choices=[('holiday', 'Public holiday'), ('in_service', 'In-service day (no students)'), ('other', 'Other closed day')], default='other', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.school')),
            ],
            options={
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['school', 'start_date', 'end_date'], name='core_school_school__c52872_idx')],
            },
        ),
    ]
