# Generated by Django 5.2.16 on 2026-07-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schoolcalendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='messaging_enabled',
            field=models.BooleanField(default=False, help_text="Turns on direct guardian ↔ teacher messaging for this school. Off by default: schools that aren't ready to support real-time parent messaging (staffing, moderation, expectations around response time) shouldn't have it forced on them. A prerequisite for MessageThread/Message below, not just a UI hint — thread-creation and thread-viewing views re-check this server-side."),
        ),
    ]
