# Generated by Django 5.2.16 on 2026-07-29 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_messagethread_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThreadRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='messagethread',
            name='unique_thread_per_guardian_teacher_student',
        ),
        migrations.AddField(
            model_name='message',
            name='removed_at',
            field=models.DateTimeField(blank=True, help_text='Class threads only. Set when the class teacher removes this message.', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_removed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='announcements_only',
            field=models.BooleanField(default=False, help_text="Class threads only. When on, only the class's teacher(s) can post — guardians can still read the thread, just not reply. A teacher-facing toggle for a class where two-way chat isn't the right fit; off (guardians can post) by default, matching how a real classroom group usually works."),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Class threads only — every guardian linked to a currently enrolled, active student in the class, plus its homeroom and co-teachers. Maintained automatically by core.messaging.sync_class_thread; never edited directly by a view. One-to-one threads use guardian/teacher instead and leave this empty.', related_name='class_message_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Set for a class thread; blank for a one-to-one thread.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='thread_type',
            field=models.CharField(choices=[('one_to_one', 'Guardian ↔ teacher'), ('class', 'Class group')], default='one_to_one', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='One-to-one threads only. Set when the other participant views it.', null=True),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='guardian',
            field=models.ForeignKey(blank=True, help_text='One-to-one threads only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_threads_as_guardian', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='student',
            field=models.ForeignKey(blank=True, help_text="Set for a one-to-one thread; blank for a class thread, which isn't scoped to a single student.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='core.student'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='One-to-one threads only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_threads_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['school', 'school_class'], name='core_messag_school__766c09_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(condition=models.Q(('thread_type', 'one_to_one')), fields=('guardian', 'teacher', 'student'), name='unique_thread_per_guardian_teacher_student'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(condition=models.Q(('thread_type', 'class')), fields=('school_class',), name='unique_thread_per_class'),
        ),
        migrations.AddField(
            model_name='messagethreadread',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='core.messagethread'),
        ),
        migrations.AddField(
            model_name='messagethreadread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='messagethreadread',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='unique_thread_read_state'),
        ),
    ]
