# Generated by Django 5.2.16 on 2026-07-29 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_schoolclass_messaging_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(help_text='The teacher (or admin, for an amended older entry) who last saved this row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_taken', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['school_class', 'date'], name='core_attend_school__f2618a_idx'), models.Index(fields=['student', '-date'], name='core_attend_student_f91b7b_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_attendance_per_student_day')],
            },
        ),
    ]
