# Generated by Django 5.2.16 on 2026-07-29 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('comment', models.TextField(blank=True, help_text='Optional narrative comment, shown alongside the subject rows.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text="The teacher (or admin, on a teacher's behalf) who last saved this report.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards_created', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.student')),
            ],
            options={
                'ordering': ['-term__start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(help_text='Free text — a letter grade, a percentage, or a descriptive mark.', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Controls display order on the report.')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.reportcard')),
            ],
            options={
                'ordering': ['order', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Term 1' or 'Quarter 2'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.school')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.term'),
        ),
        migrations.CreateModel(
            name='ReportCardRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_reads', to=settings.AUTH_USER_MODEL)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.reportcard')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report_card', 'guardian'), name='unique_report_card_read')],
            },
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_term_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('student', 'term'), name='unique_report_card_per_student_term'),
        ),
    ]
