# Generated by Django 5.1.6 on 2026-08-04 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_key', models.CharField(help_text='Key into core.exports.REGISTRY for the record type exported.', max_length=50)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], default='csv', max_length=3)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='class_id/date_from/date_to exactly as applied when this job was queued.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/')),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', '-created_at'], name='core_export_school__07ad6d_idx')],
            },
        ),
    ]
