"""
Django settings for notipa project.

Generated by 'django-admin startproject' using Django 6.0.7,
then adapted for environment-driven configuration (SQLite in
development, PostgreSQL in production) and Docker deployment.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)

# Reads a local .env file if one exists (e.g. running manage.py directly
# outside Docker). Inside Docker, env vars are already supplied via
# env_file in docker-compose.yml / docker-compose.prod.yml, so this is a
# no-op there.
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)

DJANGO_ENV = env('DJANGO_ENV', default='development')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-pa*(exmq_*vq$mgfh+c5g^y9k=htu++0#ktp0lqg_+y^*wyj&m')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=(DJANGO_ENV != 'production'))

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

# Custom user model (core.User) — replaces Django's default. Must be set
# before the first migration; email is optional and phone_number is the
# identifier that matters for guardians invited via SMS/link with no
# email address (proposal Section 4.2).
AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Must come after AuthenticationMiddleware — resolves request.user's
    # active SchoolMembership onto request.school / request.membership.
    # This is the enforcement seam for row-level multi-tenancy: views
    # scope querysets by request.school, never by a client-supplied ID.
    'core.middleware.ActiveSchoolMiddleware',
]

# Authentication — standard Django username/password login for now.
# Passwordless SMS-based guardian invites (proposal Section 4.2) are a
# separate, later mechanism layered on top of the same core.User model;
# this is just the login/logout plumbing every role needs regardless.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'login'

ROOT_URLCONF = 'notipa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'notipa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Development (DJANGO_ENV=development, the default): SQLite, stored on the
# notipa_dev_db named Docker volume at /app/data — not inside the code bind
# mount, so it survives image rebuilds.
#
# Production (DJANGO_ENV=production): PostgreSQL, running as its own
# 'db' service on the notipa_prod_db named volume. See docker-compose.prod.yml.

if DJANGO_ENV == 'production':
    DATABASES = {
        'default': {
            'ENGINE': env('DB_ENGINE', default='django.db.backends.postgresql'),
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST', default='db'),
            'PORT': env('DB_PORT', default='5432'),
        }
    }
else:
    DATA_DIR = BASE_DIR / 'data'
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DATA_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
#
# Served via WhiteNoise directly from the 'web' container in production —
# no separate Nginx-in-Docker service needed, consistent with the
# host-level Nginx pattern used on the other droplets, but without requiring
# Nginx to reach into a Docker volume for static files.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Media files (homework attachments, student record uploads)
# https://docs.djangoproject.com/en/6.0/topics/files/
#
# Local filesystem storage for now (fine for the pilot). Proposal Section 5
# flags object storage (S3-compatible — DigitalOcean Spaces) as the
# eventual backend; swapping STORAGES['default'] later doesn't require any
# model changes since FileField upload_to paths are storage-agnostic.

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
